-- Insert scaffolded Phase 2 listings
BEGIN;
INSERT INTO businesses (profile_id, name, phone_encrypted, email_encrypted, suburb_id, bio, abn, abn_verified, verification_status, resource_type, is_scaffolded, is_claimed) VALUES (NULL, 'Loose Lead Training', pgp_sym_encrypt('0411000101', current_setting('pgcrypto.key')), pgp_sym_encrypt('hello@looselead.com', current_setting('pgcrypto.key')), (SELECT id FROM suburbs WHERE name = 'Fitzroy' LIMIT 1), 'Scraped entry for Loose Lead Training', '12345678901', false, 'manual_review', 'trainer', true, false);
INSERT INTO trainer_specializations (business_id, age_specialty) VALUES (currval('businesses_id_seq'), 'adolescent_6_18m');
INSERT INTO trainer_behavior_issues (business_id, behavior_issue) VALUES (currval('businesses_id_seq'), 'leash_reactivity');
INSERT INTO trainer_services (business_id, service_type, is_primary) VALUES (currval('businesses_id_seq'), 'behaviour_consultations', true);
INSERT INTO trainer_services (business_id, service_type, is_primary) VALUES (currval('businesses_id_seq'), 'puppy_training', false);
INSERT INTO trainer_services (business_id, service_type, is_primary) VALUES (currval('businesses_id_seq'), 'obedience_training', false);
INSERT INTO abn_verifications (business_id, abn, business_name, matched_name, similarity_score, verification_method, status) VALUES (currval('businesses_id_seq'), '12345678901', 'Loose Lead Training', 'Loose Lead Training', 0.00, 'manual_upload', 'manual_review');
INSERT INTO businesses (profile_id, name, phone_encrypted, email_encrypted, suburb_id, bio, abn, abn_verified, verification_status, resource_type, is_scaffolded, is_claimed) VALUES (NULL, 'Puppy Basics Preston', pgp_sym_encrypt('0411000102', current_setting('pgcrypto.key')), pgp_sym_encrypt('info@puppybasicspreston.com', current_setting('pgcrypto.key')), (SELECT id FROM suburbs WHERE name = 'Preston' LIMIT 1), 'Scraped entry for Puppy Basics Preston', '12345678902', false, 'manual_review', 'trainer', true, false);
INSERT INTO trainer_specializations (business_id, age_specialty) VALUES (currval('businesses_id_seq'), 'puppies_0_6m');
INSERT INTO trainer_behavior_issues (business_id, behavior_issue) VALUES (currval('businesses_id_seq'), 'recall_issues');
INSERT INTO trainer_services (business_id, service_type, is_primary) VALUES (currval('businesses_id_seq'), 'group_classes', true);
INSERT INTO trainer_services (business_id, service_type, is_primary) VALUES (currval('businesses_id_seq'), 'puppy_training', false);
INSERT INTO trainer_services (business_id, service_type, is_primary) VALUES (currval('businesses_id_seq'), 'obedience_training', false);
INSERT INTO abn_verifications (business_id, abn, business_name, matched_name, similarity_score, verification_method, status) VALUES (currval('businesses_id_seq'), '12345678902', 'Puppy Basics Preston', 'Puppy Basics Preston', 0.00, 'manual_upload', 'manual_review');
INSERT INTO businesses (profile_id, name, phone_encrypted, email_encrypted, suburb_id, bio, abn, abn_verified, verification_status, resource_type, is_scaffolded, is_claimed) VALUES (NULL, 'Senior Dog Specialists', pgp_sym_encrypt('0411000103', current_setting('pgcrypto.key')), pgp_sym_encrypt('contact@senior-dog.com', current_setting('pgcrypto.key')), (SELECT id FROM suburbs WHERE name = 'Box Hill' LIMIT 1), 'Scraped entry for Senior Dog Specialists', '12345678903', false, 'manual_review', 'trainer', true, false);
INSERT INTO trainer_specializations (business_id, age_specialty) VALUES (currval('businesses_id_seq'), 'senior_7y_plus');
INSERT INTO trainer_behavior_issues (business_id, behavior_issue) VALUES (currval('businesses_id_seq'), 'anxiety_general');
INSERT INTO trainer_services (business_id, service_type, is_primary) VALUES (currval('businesses_id_seq'), 'private_training', true);
INSERT INTO trainer_services (business_id, service_type, is_primary) VALUES (currval('businesses_id_seq'), 'puppy_training', false);
INSERT INTO trainer_services (business_id, service_type, is_primary) VALUES (currval('businesses_id_seq'), 'obedience_training', false);
INSERT INTO abn_verifications (business_id, abn, business_name, matched_name, similarity_score, verification_method, status) VALUES (currval('businesses_id_seq'), '12345678903', 'Senior Dog Specialists', 'Senior Dog Specialists', 0.00, 'manual_upload', 'manual_review');
INSERT INTO businesses (profile_id, name, phone_encrypted, email_encrypted, suburb_id, bio, abn, abn_verified, verification_status, resource_type, is_scaffolded, is_claimed) VALUES (NULL, 'Westside Training', pgp_sym_encrypt('0411000104', current_setting('pgcrypto.key')), pgp_sym_encrypt('westside@example.com', current_setting('pgcrypto.key')), (SELECT id FROM suburbs WHERE name = 'Sunshine' LIMIT 1), 'Scraped entry for Westside Training', '12345678904', false, 'manual_review', 'trainer', true, false);
INSERT INTO trainer_specializations (business_id, age_specialty) VALUES (currval('businesses_id_seq'), 'adult_18m_7y');
INSERT INTO trainer_behavior_issues (business_id, behavior_issue) VALUES (currval('businesses_id_seq'), 'destructive_behaviour');
INSERT INTO trainer_services (business_id, service_type, is_primary) VALUES (currval('businesses_id_seq'), 'obedience_training', true);
INSERT INTO trainer_services (business_id, service_type, is_primary) VALUES (currval('businesses_id_seq'), 'puppy_training', false);
INSERT INTO trainer_services (business_id, service_type, is_primary) VALUES (currval('businesses_id_seq'), 'behaviour_consultations', false);
INSERT INTO abn_verifications (business_id, abn, business_name, matched_name, similarity_score, verification_method, status) VALUES (currval('businesses_id_seq'), '12345678904', 'Westside Training', 'Westside Training', 0.00, 'manual_upload', 'manual_review');
INSERT INTO businesses (profile_id, name, phone_encrypted, email_encrypted, suburb_id, bio, abn, abn_verified, verification_status, resource_type, is_scaffolded, is_claimed) VALUES (NULL, 'Eastern Behaviour Labs', pgp_sym_encrypt('0411000105', current_setting('pgcrypto.key')), pgp_sym_encrypt('lab@example.com', current_setting('pgcrypto.key')), (SELECT id FROM suburbs WHERE name = 'Croydon' LIMIT 1), 'Scraped entry for Eastern Behaviour Labs', '12345678905', false, 'manual_review', 'trainer', true, false);
INSERT INTO trainer_specializations (business_id, age_specialty) VALUES (currval('businesses_id_seq'), 'adolescent_6_18m');
INSERT INTO trainer_behavior_issues (business_id, behavior_issue) VALUES (currval('businesses_id_seq'), 'resource_guarding');
INSERT INTO trainer_services (business_id, service_type, is_primary) VALUES (currval('businesses_id_seq'), 'behaviour_consultations', true);
INSERT INTO trainer_services (business_id, service_type, is_primary) VALUES (currval('businesses_id_seq'), 'puppy_training', false);
INSERT INTO trainer_services (business_id, service_type, is_primary) VALUES (currval('businesses_id_seq'), 'obedience_training', false);
INSERT INTO abn_verifications (business_id, abn, business_name, matched_name, similarity_score, verification_method, status) VALUES (currval('businesses_id_seq'), '12345678905', 'Eastern Behaviour Labs', 'Eastern Behaviour Labs', 0.00, 'manual_upload', 'manual_review');
COMMIT;