#!/usr/bin/env python3
"""Regenerate implementation-derived SSOT snapshots.

This script intentionally produces *summaries*, not full source copies.
It is used to prevent docs drift by making inventories generated and CI-enforced.

Outputs:
- DOCS/SSOT/_generated/routes.md
- DOCS/SSOT/_generated/api.md
- DOCS/SSOT/_generated/edge_functions.md
- DOCS/SSOT/_generated/schema.md
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


REPO_ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = REPO_ROOT / "DOCS" / "SSOT" / "_generated"

APP_DIR = REPO_ROOT / "src" / "app"
API_DIR = APP_DIR / "api"
EDGE_FUNCTIONS_DIR = REPO_ROOT / "supabase" / "functions"
SCHEMA_SQL = REPO_ROOT / "supabase" / "schema.sql"


def write_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n", encoding="utf-8")


def iter_files(root: Path, name: str) -> Iterable[Path]:
    if not root.exists():
        return []
    for p in root.rglob(name):
        if p.is_file():
            yield p


def to_route(path: Path) -> str:
    # Convert src/app/.../page.tsx to a Next.js route.
    rel = path.relative_to(APP_DIR)
    parts = list(rel.parts)
    if parts[-1] in ("page.tsx", "page.ts", "page.jsx", "page.js"):
        parts = parts[:-1]
    route = "/" + "/".join(parts)
    route = route.replace("/index", "")
    return route if route != "/" else "/"


def generate_routes_md() -> str:
    pages = sorted({to_route(p) for p in iter_files(APP_DIR, "page.tsx")})

    public_pages = [r for r in pages if not r.startswith("/admin")]
    admin_pages = [r for r in pages if r.startswith("/admin")]

    lines: list[str] = []
    lines.append("# Generated Routes Snapshot")
    lines.append("")
    lines.append("This file is generated by `scripts/ssot_refresh.py`. Do not edit by hand.")
    lines.append("")
    lines.append("## Public pages")
    for r in public_pages:
        lines.append(f"- `{r}`")

    lines.append("")
    lines.append("## Admin pages")
    for r in admin_pages:
        lines.append(f"- `{r}`")

    lines.append("")
    lines.append("## Notes")
    lines.append("- This snapshot lists routes based on `src/app/**/page.tsx` discovery.")
    lines.append("- Redirect handlers are represented by their page routes; see implementation for details.")

    return "\n".join(lines)


@dataclass(frozen=True)
class ApiEndpoint:
    route: str
    methods: tuple[str, ...]


_METHOD_RE = re.compile(r"^export\s+async\s+function\s+(GET|POST|PUT|PATCH|DELETE|OPTIONS)\b")


def generate_api_md() -> str:
    endpoints: list[ApiEndpoint] = []

    for route_file in iter_files(API_DIR, "route.ts"):
        rel = route_file.relative_to(API_DIR)
        parts = list(rel.parts)
        parts = parts[:-1]  # drop route.ts
        route = "/api/" + "/".join(parts)

        methods: list[str] = []
        for line in route_file.read_text(encoding="utf-8", errors="replace").splitlines():
            m = _METHOD_RE.match(line.strip())
            if m:
                methods.append(m.group(1))

        endpoints.append(ApiEndpoint(route=route, methods=tuple(sorted(set(methods)))))

    endpoints.sort(key=lambda e: e.route)

    lines: list[str] = []
    lines.append("# Generated API Snapshot")
    lines.append("")
    lines.append("This file is generated by `scripts/ssot_refresh.py`. Do not edit by hand.")
    lines.append("")

    for e in endpoints:
        methods = ", ".join(e.methods) if e.methods else "(no HTTP methods detected)"
        lines.append(f"- `{e.route}` — {methods}")

    lines.append("")
    lines.append("## Notes")
    lines.append("- Methods are detected via `export async function METHOD(...)` in `route.ts` files.")

    return "\n".join(lines)


def generate_edge_functions_md() -> str:
    lines: list[str] = []
    lines.append("# Generated Edge Functions Snapshot")
    lines.append("")
    lines.append("This file is generated by `scripts/ssot_refresh.py`. Do not edit by hand.")
    lines.append("")

    if not EDGE_FUNCTIONS_DIR.exists():
        lines.append("No `supabase/functions` directory found.")
        return "\n".join(lines)

    functions: list[str] = []
    for child in sorted(EDGE_FUNCTIONS_DIR.iterdir()):
        if not child.is_dir():
            continue
        if child.name.startswith("_"):
            continue
        if (child / "index.ts").exists():
            functions.append(child.name)

    if not functions:
        lines.append("No Edge Functions detected.")
        return "\n".join(lines)

    for fn in functions:
        lines.append(f"- `{fn}`")

    lines.append("")
    lines.append("## Notes")
    lines.append("- This snapshot lists function directories containing `index.ts`.")

    return "\n".join(lines)


_CREATE_TABLE_RE = re.compile(r"^CREATE\s+TABLE\s+public\.([a-zA-Z0-9_]+)\s*\(")
_CREATE_TYPE_RE = re.compile(r"^CREATE\s+TYPE\s+public\.([a-zA-Z0-9_]+)\s+AS\s+ENUM\s*\(")
_CREATE_FUNCTION_RE = re.compile(r"^CREATE\s+FUNCTION\s+public\.([a-zA-Z0-9_]+)\s*\(")


def generate_schema_md() -> str:
    lines: list[str] = []
    lines.append("# Generated Schema Snapshot")
    lines.append("")
    lines.append("This file is generated by `scripts/ssot_refresh.py`. Do not edit by hand.")
    lines.append("")

    if not SCHEMA_SQL.exists():
        lines.append("Missing `supabase/schema.sql`.")
        return "\n".join(lines)

    text = SCHEMA_SQL.read_text(encoding="utf-8", errors="replace").splitlines()

    tables: set[str] = set()
    enums: set[str] = set()
    functions: set[str] = set()

    for raw in text:
        line = raw.strip()
        m = _CREATE_TABLE_RE.match(line)
        if m:
            tables.add(m.group(1))
            continue
        m = _CREATE_TYPE_RE.match(line)
        if m:
            enums.add(m.group(1))
            continue
        m = _CREATE_FUNCTION_RE.match(line)
        if m:
            functions.add(m.group(1))
            continue

    lines.append("## Tables")
    for t in sorted(tables):
        lines.append(f"- `{t}`")

    lines.append("")
    lines.append("## Enums")
    for e in sorted(enums):
        lines.append(f"- `{e}`")

    lines.append("")
    lines.append("## RPC / SQL functions")
    for f in sorted(functions):
        lines.append(f"- `{f}`")

    lines.append("")
    lines.append("## Notes")
    lines.append("- Source: `supabase/schema.sql` (derived snapshot in this repo).")

    return "\n".join(lines)


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    write_file(OUT_DIR / "routes.md", generate_routes_md())
    write_file(OUT_DIR / "api.md", generate_api_md())
    write_file(OUT_DIR / "edge_functions.md", generate_edge_functions_md())
    write_file(OUT_DIR / "schema.md", generate_schema_md())

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
